# 
ts: &defaults
  adapter: postgresql
  username: audit_user
  password: 123
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000


#   adapter: sqlserver
#   database: suryodaya_testdb
#   pool: 5
#   username: SA
#   password: Audit360!$
#   host: 10.10.10.11
#   port: 1433
#   enocoding: utf8


development:
  database: practise_dev #accion_server_production #pact_uat_server_production #pact_server_production #latest_audit_360_local #accion_server_production # #audit_360_qa_prod #ola_master #audit_360_qa_prod #audit_360_dev #latest_audit_360_nocpl
  <<: *defaults


# development:
#   database: audit_360_nocpl #accion_server_production #pact_uat_server_production #pact_server_production #latest_audit_360_local #accion_server_production # #audit_360_qa_prod #ola_master #audit_360_qa_prod #audit_360_dev #latest_audit_360_nocpl
#   <<: *defaults

production:
  database: practise_dev #accion_server_production #pact_uat_server_production #pact_server_production #latest_audit_360_local #accion_server_production # #audit_360_qa_prod #ola_master #audit_360_qa_prod #audit_360_dev #latest_audit_360_nocpl
  <<: *defaults



  # SQLite version 3.x
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem 'sqlite3'
# #
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3